// Every real-backend URL path used by services/*.ts, in one place.
// Paths are relative to apiClient's baseURL (VITE_API_BASE_URL).
export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    signup: '/auth/signup',
    verifyOtp: '/auth/verify-otp',
    resendOtp: '/auth/resend-otp',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    logout: '/auth/logout',
    socialLogin: '/auth/social-login',
    refresh: '/auth/refresh',
  },
  users: {
    byId: (userId: string) => `/users/${userId}`,
    me: '/users/me',
    dmChannel: (userId: string) => `/users/${userId}/dm-channel`,
    notificationPreferences: '/users/me/notification-preferences',
    privacy: '/users/me/privacy',
  },
  account: {
    changeEmail: '/account/email',
    verifyEmailChange: '/account/email/verify',
    changePhone: '/account/phone',
    verifyPhoneChange: '/account/phone/verify',
    changePassword: '/account/password',
    deleteAccount: '/account/delete',
  },
  clubs: {
    myClubs: '/me/clubs',
    list: '/clubs',
    bySlug: (slug: string) => `/clubs/${slug}`,
    join: (clubId: string) => `/clubs/${clubId}/join`,
    myMembership: (clubId: string) => `/clubs/${clubId}/members/me`,
    members: (clubId: string) => `/clubs/${clubId}/members`,
    events: (clubId: string) => `/clubs/${clubId}/events`,
    channels: (clubId: string) => `/clubs/${clubId}/channels`,
  },
  events: {
    list: '/events',
    byId: (eventId: string) => `/events/${eventId}`,
    rsvp: (eventId: string) => `/events/${eventId}/rsvp`,
  },
  chat: {
    myConversations: '/me/conversations',
    messages: (channelId: string) => `/channels/${channelId}/messages`,
    message: (messageId: string) => `/messages/${messageId}`,
    reactions: (messageId: string) => `/messages/${messageId}/reactions`,
    vote: (messageId: string) => `/messages/${messageId}/vote`,
    pin: (channelId: string) => `/channels/${channelId}/pin`,
    read: (channelId: string) => `/channels/${channelId}/read`,
  },
  notifications: {
    list: '/me/notifications',
    markRead: '/me/notifications/mark-read',
  },
  invitations: {
    list: '/me/invitations',
    accept: (invitationId: string) => `/me/invitations/${invitationId}/accept`,
    decline: (invitationId: string) => `/me/invitations/${invitationId}/decline`,
  },
  savedClubs: {
    list: '/me/saved-clubs',
    save: (clubId: string) => `/me/saved-clubs/${clubId}`,
    unsave: (clubId: string) => `/me/saved-clubs/${clubId}`,
  },
  payments: {
    subscriptions: '/users/me/subscriptions',
    transactions: '/users/me/transactions',
    cancelSubscription: (subscriptionId: string) => `/subscriptions/${subscriptionId}`,
    paymentMethods: '/users/me/payment-methods',
    paymentMethod: (id: string) => `/users/me/payment-methods/${id}`,
    billingAddress: '/users/me/billing-address',
  },
  content: {
    about: '/content/about',
    services: '/content/services',
    howItWorks: '/content/how-it-works',
    contact: '/content/contact',
    legal: (slug: string) => `/content/legal/${slug}`,
    submitContact: '/contact',
  },
} as const;
