export const ROUTES = {
  home: '/',
  about: '/about',
  services: '/services',
  howItWorks: '/how-it-works',
  contact: '/contact',
  terms: '/terms',
  privacyPolicy: '/privacy',
  refundPolicy: '/refund-policy',
  cookiePolicy: '/cookie-policy',
  clubs: '/clubs',
  events: '/events',
  search: '/search',
  myClubs: '/my-clubs',
  notifications: '/notifications',
  messages: '/messages',
  messageThread: (userId: string) => `/messages/${userId}`,
  profile: (userId: string) => `/profile/${userId}`,
  profileEdit: '/profile/edit',
  settings: '/settings',
  settingsNotifs: '/settings/notifications',
  settingsPrivacy: '/settings/privacy',
  settingsPayments: '/settings/payments',
  subscriptions: '/subscriptions',
  checkout: (planId: string) => `/checkout/${planId}`,
  checkoutSuccess: '/checkout/success',
  checkoutFailure: '/checkout/failure',
  login: '/login',
  signup: '/signup',
  signupSuccess: '/signup/success',
  verifyOtp: '/verify-otp',
  forgotPassword: '/forgot-password',
  authCallback: '/auth/callback',
  onboardingProfile: '/onboarding/profile',
  onboardingInterests: '/onboarding/interests',
  clubLanding: (slug: string) => `/clubs/${slug}`,
  eventDetail: (slug: string, eventId: string) => `/clubs/${slug}/events/${eventId}`,
  clubDashboard: (slug: string) => `/clubs/${slug}/dashboard`,
  clubChat: (slug: string) => `/clubs/${slug}/dashboard/chat`,
  clubEvents: (slug: string) => `/clubs/${slug}/dashboard/events`,
  clubEventDetail: (slug: string, eventId: string) => `/clubs/${slug}/dashboard/events/${eventId}`,
  clubAlbums: (slug: string) => `/clubs/${slug}/dashboard/albums`,
  clubAlbumDetail: (slug: string, albumId: string) => `/clubs/${slug}/dashboard/albums/${albumId}`,
  clubMembers: (slug: string) => `/clubs/${slug}/dashboard/members`,
  clubMemberProfile: (slug: string, userId: string) => `/clubs/${slug}/dashboard/members/${userId}`,
  clubAbout: (slug: string) => `/clubs/${slug}/dashboard/about`,
  clubPayments: (slug: string) => `/clubs/${slug}/dashboard/payments`,
  notFound: '/404',
  unauthorized: '/unauthorized',
  maintenance: '/maintenance',
} as const;
